force-app/main/default/objects/AccountLog__c/AccountLog__c.object-meta.xml
<CustomObject>
    <label>Account Log</label>
    <nameField>
        <label>Account Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountLog__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Logs</relationshipLabel>
    <relationshipName>Account_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountLog__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OOPS/Composition/GoodExample_Composition/CreateAccountLogAction.cls
public class CreateAccountLogAction implements AccountCreationAction {
    public void createAccounts(List<Account> accounts) {
        List<AccountLog__c> accountLogs = new List<AccountLog__c>();

        for (Account acc : accounts) {
            accountLogs.add(new AccountLog__c(
                Account__c = acc.Id,
                Action__c = 'Account Created'
            ));
        
            System.debug('📝 Log entry created for Account: ' + acc.Name);
        }
        
        insert accountLogs;
    }
}