force-app/main/default/objects/AccountLog__c/AccountLog__c.object-meta.xml
<CustomObject>
    <label>Account Log</label>
    <nameField>
        <label>Account Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountLog__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Logs</relationshipLabel>
    <relationshipName>Account_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountLog__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OOPS/Composition/BadExample_Inheritance/AllAcountCReationActions_Inheritance.cls
public with sharing class AllAcountCReationActions_Inheritance extends AccountCreationAction_Inheritance {
    public override void createAccounts (List<Account> accounts) {
        super.createAccounts(accountsl);

        List<AccountLog__c> accountLogs = new List<AccountLog__c>();
        for (Account acc : accounts) {
            System.debug('Welcome email send to : ' + acc.Name);
            accountLogs.add(new AccountLog__c(
                Account__c = acc.Id,
                Action__c = 'Account Created'
            ));
        }

        insert accountLogs;

        //! Allot of code duplication here which violates the Single Responsibility Principle (a SOLID Principle)
    }
}